spring:
  application:
    name: Task-hub
  config:
    activate:
      on-profile: default
  data:
    redis:
      host: localhost
      port: 6380
      database: 0
    mongodb:
      uri: mongodb://root:root@localhost:27017/task_db?authSource=admin
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/task_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      default_schema: public
      database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  cache:
    ttl-seconds: 300
  security:
    jwt:
      access-token-expiration: 86400000
      refresh-token-expiration: 684000000
    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail